name: untitled05
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  #UI
  cupertino_icons: any
  material_design_icons_flutter: any
  sizer: any
  auto_size_text: any
  bot_toast: any
  flutter_spinkit: any
  #Core
  flutter_hooks: any
  stacked: any
  stacked_services: any
  auto_route: any
  #NETWORK
  dio: any
  dio_interceptors: any
  dio_logging_interceptor: any
  dio_cache_interceptor: any
  dio_http_cache: any
  pretty_dio_logger: any
  dio_logger: any
  connectivity_plus: any
  #Utils
  intl: any
  json_annotation: any
  freezed_annotation: any
  equatable: any
  built_value: any
  dartz: any
  logger: any
  flutter_phoenix: any
  device_preview: any
  requests_inspector: any
  #Testing
  mockito: any

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: any
  build_runner: any
  json_serializable: any
  freezed: any

dependency_overrides:
  device_preview: 1.0.0
  json_annotation: 4.8.0
  freezed_annotation: 2.2.0
  build_runner: 2.3.3
  json_serializable: 6.6.1
  freezed: 2.3.2

flutter:
  uses-material-design: true

  assets:
    - assets/
